name = "bofa-qqbot"
main = "src/index.ts"
compatibility_date = "2026-08-15"

[[routes]]
pattern = "bot.efa-tech.dev/qq*"
zone_name = "efa-tech.dev"

[[routes]]
pattern = "bot.efa-tech.dev/event*"
zone_name = "efa-tech.dev"

[[kv_namespaces]]
binding = "CONFIG"
id = "b04bf208983943b89db45dc21403b5e7"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
